[build]
  command = "npm run build"
  publish = "build"
  functions = "functions-build"

[dev]
  command = "react-scripts start"

[template.environment]
  REACT_APP_AUTH0_DOMAIN = "Auth0 application domain"
  REACT_APP_AUTH0_CLIENT_ID = "Auth0 application client id"
  AUTH0_CLIENT_SECRET_B64 = "Auth0 application client secret"
  AUTH0_CLIENT_ID_BACKEND = "Auth0 machine-to-machine client id"
  AUTH0_CLIENT_SECRET_BACKEND_B64 = "Auth0 machine-to-machine client secret"
  REACT_APP_AUTH0_CLAIM_NAMESPACE = "(http://host.com) Auth0 namespace for custom claims"
  NEXMO_APP_ID = "Your nexmo application id"
  NEXMO_APP_PRIV_KEY_B64 = "Your nexmo application private key in base64"
  NEXMO_JTW_ISS_NAME = "The issuer field for the nexmo JWT"
  REACT_APP_NEXMO_PHONE_NUMBER = "Your nexmo phone number linked to your application"
